spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: postgres
    password: Oitentaeum81
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

